# Numpy Arrays

## Just like an Array; what we can also say that it is like a data mining tool for Python

In [1]:
import numpy as np

In [4]:
a=np.array([1,2,3,4])     ## Directly make an array

In [27]:
a

array([1, 2, 3, 4])

In [48]:
a.dtype

dtype('int32')

***************************************

In [7]:
lst=[1,2,3]

In [9]:
b=np.array(lst)

In [11]:
b                        ## Making an array from list

array([1, 2, 3])

In [12]:
a.shape

(4,)

In [13]:
a.size

4

***********************************************************

In [14]:
lst1=[3,4,5]
lst2=[7,8,9]
lst3=[11,12,13]

In [16]:
nlst=[lst1,lst2,lst3]

In [17]:
nlst    ### Combining different lists

[[3, 4, 5], [7, 8, 9], [11, 12, 13]]

In [18]:
nlst1=np.array(nlst)

In [20]:
nlst1                      ### Converting the combination of list into combination of array

array([[ 3,  4,  5],
       [ 7,  8,  9],
       [11, 12, 13]])

In [23]:
nlst1.shape

(3, 3)

In [24]:
nlst1.size

9

********************************************

In [30]:
b=np.arange(0,10)    ### It gives us the array from start range till end range; evenly spaced

In [31]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
c=np.arange(0,10,3)    ### Here, we have given the step value 

In [35]:
c

array([0, 3, 6, 9])

In [60]:
### Basic command is np.arange(start value, end value,step value )

In [39]:
np.zeros(3)  ## Gives the zero array with one row

array([0., 0., 0.])

In [42]:
np.zeros((3,3))  ## Kindly remember the brackets we need to give; it gives 3 rows & 3 Columns

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [58]:
## Basic Command np.zeros((rows,columns))

In [45]:
np.ones(3)     ## Gives an array of 1 with 1 row

array([1., 1., 1.])

In [51]:
b=np.ones((4,2))    ## kindly remember extra bracket given; gives an array of 1 with 4 rows & 2 columns

In [52]:
b.dtype

dtype('float64')

In [59]:
## Basic Command np.ones((rows,columns))

In [53]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [54]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [57]:
## Basic command is np.linspace(start value, end value, number of total values in the array created)

In [81]:
## Difference between linspace & arrange is that of last which in arange is step value in the array & linspace is number of total values in array. In general, if anyone asks we can say linspace produce more evenly spaced arrays as compared to arange

In [82]:
np.eye(4)                      ## Creates an identity matrix; rows & columns are based on the number of 1s given

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

*****************************************

In [83]:
d=np.arange(30)

In [84]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [85]:
d.shape

(30,)

In [86]:
e=d.reshape(5,6)   ## With the help of this function, we can reshape any array into given number of rows & columns given that current rows X columns is equal to future(which we are trying to convert) Rows X Columns 

In [87]:
e

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [88]:
e.shape

(5, 6)

In [89]:
f=e.reshape(15,2)

In [90]:
f

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [91]:
f.shape

(15, 2)

******************************************************************************

In [97]:
np.random.rand(4)                               ## This Creates an array of specified shape & fills with random value`

array([0.77556321, 0.79136231, 0.30931382, 0.52416196])

In [98]:
np.random.rand(3,4)                         ## The first one is row & second one is column

array([[0.9252681 , 0.03275391, 0.04148149, 0.44003516],
       [0.79696299, 0.97425026, 0.47014743, 0.31772769],
       [0.52972873, 0.16024974, 0.30695258, 0.193944  ]])

In [99]:
np.random.rand(3,4,5)            ## The First one is row, second one is column, while in third the entire matrix is considered one element & third number creates equivalent number of matrix; just like row & this sequence follow as we introduce more arguments in rand function

array([[[0.18404947, 0.70543392, 0.46897422, 0.10815674, 0.4167696 ],
        [0.00140763, 0.26194358, 0.65689889, 0.66109271, 0.40621524],
        [0.2349919 , 0.54273584, 0.44579642, 0.79195496, 0.02474838],
        [0.25716475, 0.37331207, 0.26706764, 0.37973422, 0.1929426 ]],

       [[0.59326623, 0.07804284, 0.45536298, 0.20896651, 0.56832011],
        [0.58664675, 0.99470948, 0.28115655, 0.07250133, 0.63617598],
        [0.37393639, 0.95041786, 0.6106702 , 0.21407954, 0.27341908],
        [0.92759598, 0.97220775, 0.09923155, 0.98148855, 0.13951623]],

       [[0.51979069, 0.41841513, 0.50948918, 0.43926275, 0.85546434],
        [0.77639266, 0.75215542, 0.48194472, 0.94427555, 0.62521992],
        [0.97702417, 0.67711719, 0.5396651 , 0.00908318, 0.27603156],
        [0.3752821 , 0.74021272, 0.17010878, 0.22384521, 0.39345869]]])

In [128]:
## Basic Command np.random.rand(a1,a2,a3,a4,a5,a6,...........); it return values from [0,1)

***************************************************************

In [112]:
np.random.randint(5)   ## It will take positive random number less than 5

1

In [103]:
np.random.randint(4,9)   ### Gives a random integer number between given set of numbers

4

In [104]:
np.random.randint(-7,-1)

-2

In [109]:
np.random.randint(4.23,9.333)              ## Hence, number can be decimal ones also

7

In [110]:
np.random.randint(4,9,13)   ## Here, 13 is the size of the random values generated

array([5, 5, 7, 8, 7, 6, 4, 8, 7, 7, 7, 7, 7])

In [114]:
## Basic Command np.random.randint(low value, high value, size)

*********************************************************************************************

In [118]:
x=np.random.randn(2)

In [119]:
x

array([ 0.23130316, -0.01172605])

In [120]:
x.shape

(2,)

In [121]:
y=np.random.randn(3,4)

In [122]:
y

array([[-2.10365373, -1.82309368, -3.12007897,  0.13483883],
       [ 0.86571987,  2.02645403, -0.61400004,  0.71737309],
       [ 0.19674246, -0.86619289,  0.66520988,  0.24639708]])

In [123]:
y.shape

(3, 4)

In [124]:
z=np.random.randn(3,4,5)

In [125]:
z

array([[[ 0.59877586, -0.33948355, -1.6372835 , -1.32709654,
         -0.72780216],
        [ 0.28044132, -0.19484642,  1.13802325, -0.85196616,
          0.04895654],
        [ 0.1167407 , -0.18902439, -0.83222609, -1.28616099,
         -1.49780917],
        [ 0.46711109, -0.93328864, -1.41864512, -0.42415965,
          1.12002157]],

       [[-0.83028349,  0.94642481,  1.00931268, -1.98108768,
         -0.19615188],
        [ 0.81242247, -0.1518857 , -0.55154831,  0.48792803,
          0.64846816],
        [-0.77930774,  1.22828263,  0.4275976 , -0.37709292,
         -0.3108358 ],
        [-0.43900027,  0.76990983, -0.05260779, -0.35051119,
          0.09047551]],

       [[ 0.69018874,  0.08997222, -0.51079263,  0.41136328,
         -0.34591307],
        [ 0.20209068,  0.47858763, -0.30544874,  0.88920196,
          1.76553677],
        [ 1.10138042, -0.84715782, -0.86373998, -0.19500109,
          0.52286878],
        [ 1.87155883,  1.03520354,  1.14204179, -0.22201918,
          2

In [126]:
z.shape

(3, 4, 5)

In [127]:
## As we can see from the above randn is working same as that of rand but difference is that it is taking negative values also which is not in case of rand

*************************************

In [129]:
## Randn is returning values from Univariate "Gaussian"(Normal) distribution having a mean of 0 & Variance of 1

In [130]:
## I hope the difference between the rand() & randint() is cleared

******************************************

In [131]:
xx=np.random.rand(3,4)

In [142]:
xx

array([[0.90328152, 0.64721204, 0.01654289, 0.718519  ],
       [0.66446775, 0.27464994, 0.07248398, 0.19390696],
       [0.89006328, 0.43190519, 0.42982441, 0.9826758 ]])

In [145]:
xx.max()            ## Maximum Value   alternative command np.max(xx)

0.9826757962011959

In [146]:
xx.min()    ## Minimum Value alternative command np.min(xx)

0.01654288918516167

In [147]:
xx.argmax()      ## Position of Maximum Value alternative command np.argmax(xx)

11

In [148]:
xx.argmin()         ## Position of minimum value alternative command np.argmin(xx)

2

In [153]:
xx.mean()             ## Mean of array alternative command np.mean(xx)

0.5187943951095064

In [154]:
xx.std()              ## Standard deviation of array; alternative command np.std(xx)

0.3176124399793826

In [156]:
xw=xx.sum()     ## Sum of all elements of array; alternative command np.sum(xx)

In [157]:
xw

6.225532741314077

In [158]:
xw.dtype

dtype('float64')

***************************************************

In [186]:
xx

array([[0.90328152, 0.64721204, 0.01654289, 0.718519  ],
       [0.66446775, 0.27464994, 0.07248398, 0.19390696],
       [0.89006328, 0.43190519, 0.42982441, 0.9826758 ]])

In [171]:
yy=np.random.rand(3,4)

In [183]:
yy

array([[0.66253088, 0.06746736, 0.00918724, 0.83746317],
       [0.00707579, 0.11478244, 0.37852077, 0.78313106],
       [0.35101455, 0.95072036, 0.49172395, 0.86103207]])

In [172]:
zz=np.random.rand(4,3)

In [173]:
vv=xx+yy  ### Sum of 2 arrays

In [184]:
zz

array([[0.03538514, 0.80514986, 0.58518712],
       [0.12036493, 0.1145871 , 0.76870149],
       [0.89569942, 0.17806129, 0.97147865],
       [0.77865736, 0.62541924, 0.19011403]])

In [174]:
vv

array([[1.56581239, 0.71467941, 0.02573013, 1.55598217],
       [0.67154353, 0.38943238, 0.45100475, 0.97703802],
       [1.24107783, 1.38262555, 0.92154836, 1.84370787]])

In [175]:
vv=xx+zz ## Sum can be done in arrays if they are equal in number of rows & columns

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [176]:
vx= xx-yy ## Difference of array

In [177]:
vx

array([[ 0.24075064,  0.57974468,  0.00735565, -0.11894417],
       [ 0.65739196,  0.15986749, -0.3060368 , -0.5892241 ],
       [ 0.53904873, -0.51881518, -0.06189954,  0.12164372]])

In [178]:
xx-zz   ## Same condition as that of addition; should have equla number of rows & columns

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [179]:
xx/yy    ## Division of array

array([[ 1.36338026,  9.59296506,  1.80063763,  0.85797087],
       [93.90726285,  2.39278696,  0.19149273,  0.24760474],
       [ 2.53568771,  0.45429256,  0.87411729,  1.14127664]])

In [180]:
xx/zz     ## Same condition as that of the sum & difference; same number of rows & columns in both arrays

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [198]:
xx*yy

array([[5.98451893e-01, 4.36656890e-02, 1.51983485e-04, 6.01733200e-01],
       [4.70163196e-03, 3.15249909e-02, 2.74366902e-02, 1.51854563e-01],
       [3.12425163e-01, 4.10621057e-01, 2.11354956e-01, 8.46115379e-01]])

In [199]:
yy*zz     ## Same condition number of rows & columns should be equal in both arrays

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [187]:
### Here, there is a difference in what we actually do in the multiplication of matrix; here we multiply number of elements in one array with number of elements in second array; rather than number; that's why in above error is shown(Basic rule is that the number of columns of first matrix should be equal to rows of second matrix for multiplication)

In [200]:
xx@yy

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [207]:
az=xx@zz                       

In [208]:
az

array([[0.68416194, 1.2537604 , 1.17877318],
       [0.27248144, 0.70064719, 0.70724285],
       [1.23364247, 1.45724453, 1.45724542]])

In [209]:
az.shape

(3, 3)

In [203]:
## Hence, from above, we can see that to multiply the matrix , we need to @ operator rather than *

In [191]:
np.dot(xx,yy)  ### Dot Product

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [210]:
ad=np.dot(xx,zz)   

In [211]:
ad

array([[0.68416194, 1.2537604 , 1.17877318],
       [0.27248144, 0.70064719, 0.70724285],
       [1.23364247, 1.45724453, 1.45724542]])

In [212]:
ad.shape

(3, 3)

In [205]:
## Hence, we can see that dot product & @; both gives same value

In [194]:
np.matmul(xx,yy)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [195]:
np.matmul(xx,zz)

array([[0.68416194, 1.2537604 , 1.17877318],
       [0.27248144, 0.70064719, 0.70724285],
       [1.23364247, 1.45724453, 1.45724542]])

In [213]:
np.dot(4,xx)

array([[3.61312606, 2.58884817, 0.06617156, 2.87407601],
       [2.65787099, 1.09859974, 0.2899359 , 0.77562784],
       [3.56025312, 1.72762075, 1.71929763, 3.93070318]])

In [214]:
np.matmul(4,xx)

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [215]:
## Hence, we can see the first difference between the matmul & dot from above

In [219]:
## For other difference, check out the link: https://www.guru99.com/numpy-matrix-multiplication.html; easily inderstandable; also check this websitehttps://www.tutorialspoint.com/numpy/numpy_matmul.htm(do that example with matmul & then with dot; difference could be seen)

In [218]:
np.sqrt(xx)   ## To create square root of matrix

array([[0.95041124, 0.8044949 , 0.12861916, 0.847655  ],
       [0.81514891, 0.52407054, 0.26922848, 0.44034868],
       [0.94343165, 0.65719494, 0.65560995, 0.99130005]])

In [220]:
np.sin(xx)   ## Sine

array([[0.78536251, 0.60296461, 0.01654213, 0.65827053],
       [0.61664021, 0.27121001, 0.07242052, 0.19269409],
       [0.77711158, 0.41860179, 0.41671119, 0.83198487]])

In [221]:
np.cosh(xx)           ## Inverse cosine

array([[1.43646264, 1.21685554, 1.00013684, 1.26943326],
       [1.22900158, 1.03795398, 1.00262811, 1.01885893],
       [1.42295676, 1.09473001, 1.09380547, 1.52295176]])

In [227]:
np.log(xx)            ## Logarthmic

array([[-0.10172102, -0.4350813 , -4.10179893, -0.33056313],
       [-0.40876894, -1.29225795, -2.62438977, -1.64037683],
       [-0.11646272, -0.83954919, -0.84437851, -0.01747602]])

In [228]:
np.exp(xx)   ## Exponential

array([[2.46768759, 1.91020782, 1.01668048, 2.05139285],
       [1.94345584, 1.31606989, 1.07517558, 1.21398333],
       [2.43528375, 1.54018908, 1.53698762, 2.67159533]])

In [224]:
xx**2    ## Raised to power

array([[8.15917497e-01, 4.18883429e-01, 2.73667183e-04, 5.16269555e-01],
       [4.41517388e-01, 7.54325872e-02, 5.25392667e-03, 3.75999088e-02],
       [7.92212644e-01, 1.86542091e-01, 1.84749022e-01, 9.65651720e-01]])

In [225]:
xx**3

array([[7.37003193e-01, 2.71106400e-01, 4.52724588e-06, 3.70949485e-01],
       [2.93374064e-01, 2.07175552e-02, 3.80825491e-04, 7.29088398e-03],
       [7.05119385e-01, 8.05684968e-02, 7.94096393e-02, 9.48922573e-01]])

In [229]:
xx**1/3

array([[0.30109384, 0.21573735, 0.0055143 , 0.23950633],
       [0.22148925, 0.09154998, 0.02416133, 0.06463565],
       [0.29668776, 0.1439684 , 0.1432748 , 0.3275586 ]])

****************

In [239]:
np.hstack((xx,yy))  ### Horizontal Stack; remember, double brackets; number of rows should be equal in both arrays; same example could be seen below

array([[0.90328152, 0.64721204, 0.01654289, 0.718519  , 0.66253088,
        0.06746736, 0.00918724, 0.83746317],
       [0.66446775, 0.27464994, 0.07248398, 0.19390696, 0.00707579,
        0.11478244, 0.37852077, 0.78313106],
       [0.89006328, 0.43190519, 0.42982441, 0.9826758 , 0.35101455,
        0.95072036, 0.49172395, 0.86103207]])

In [240]:
np.vstack((xx,yy))   ## Similar to horizontal stack; number of columns should be same

array([[0.90328152, 0.64721204, 0.01654289, 0.718519  ],
       [0.66446775, 0.27464994, 0.07248398, 0.19390696],
       [0.89006328, 0.43190519, 0.42982441, 0.9826758 ],
       [0.66253088, 0.06746736, 0.00918724, 0.83746317],
       [0.00707579, 0.11478244, 0.37852077, 0.78313106],
       [0.35101455, 0.95072036, 0.49172395, 0.86103207]])

In [241]:
za=np.random.rand(3,5)

In [242]:
za

array([[0.64738628, 0.94980387, 0.63782681, 0.55611895, 0.82960838],
       [0.39250082, 0.64220797, 0.91787742, 0.11736822, 0.78621281],
       [0.30325759, 0.93094226, 0.18439715, 0.73890024, 0.72633492]])

In [243]:
np.hstack((xx,za))

array([[0.90328152, 0.64721204, 0.01654289, 0.718519  , 0.64738628,
        0.94980387, 0.63782681, 0.55611895, 0.82960838],
       [0.66446775, 0.27464994, 0.07248398, 0.19390696, 0.39250082,
        0.64220797, 0.91787742, 0.11736822, 0.78621281],
       [0.89006328, 0.43190519, 0.42982441, 0.9826758 , 0.30325759,
        0.93094226, 0.18439715, 0.73890024, 0.72633492]])

**********************************************************

### Indexing & Slicing

In [344]:
g=np.arange(0,10)

In [345]:
g

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [346]:
g[0]     ### Indexing

0

In [347]:
g[1] ## Indexing

1

In [348]:
g[-1]  ## Indexing; please note for last element we start from -1 for 1st element we start from 0; universal statement for all D of array

9

In [349]:
h=np.random.rand(3,4)

In [350]:
h

array([[0.68932178, 0.5573432 , 0.05008743, 0.5698604 ],
       [0.72730649, 0.23636635, 0.23313624, 0.85285662],
       [0.89096862, 0.03560241, 0.91137179, 0.33176297]])

In [351]:
h[0]

array([0.68932178, 0.5573432 , 0.05008743, 0.5698604 ])

In [352]:
h[1]

array([0.72730649, 0.23636635, 0.23313624, 0.85285662])

In [353]:
h[0][0]   ## Indexing for 2d array

0.6893217819799775

In [354]:
h[0][3]

0.5698603965565733

In [355]:
h[-1][0]

0.8909686202611445

In [356]:
h[-1][-2]

0.9113717933718412

In [358]:
g[0:3]    ## 0 is the index number & 2 is the position; always remember; the slicing is simple for 1D array

array([0, 1, 2])

In [393]:
g[0:5:3]       ## Slicing with the help of step value; 2 elements of first colon we know how to take; last element in the colon shows step value; after that(counting starts after that index position) it takes every n position(3rd in this case) element after that

array([0, 3])

In [394]:
g[0:5:4]   ## Just to explain the above

array([0, 4])

In [397]:
g[0:5:4][0]   ## To show certain element

0

In [398]:
g[0:5:4][1]   ## Just to explain

4

In [399]:
## For slicing refer to this article;https://towardsdatascience.com/indexing-and-slicing-of-1d-2d-and-3d-arrays-in-numpy-e731afff0bbe

In [285]:
h[1:3]                                     ### Select from row index 1; till 3rd position  of row(remember not columns)

array([[0.59771317, 0.16144546, 0.27637699, 0.22350937],
       [0.71056969, 0.049865  , 0.25944605, 0.24123075]])

In [288]:
h[1:2]   ## just to explain ; 1st index of row & 2nd position in row

array([[0.59771317, 0.16144546, 0.27637699, 0.22350937]])

In [295]:
h[1:3,1:4]  ## Now after slicing the row, we are going to slice the column(it's same way, 1 st index position of column & till 4th position of column)

array([[0.16144546, 0.27637699, 0.22350937],
       [0.049865  , 0.25944605, 0.24123075]])

In [301]:
h[1:3,1:2]  ## In this for column, starting from 1st index position column till 2nd position of column( not index, this starts as 1,2,3,.. till number of columns) 

array([[0.16144546],
       [0.049865  ]])

In [381]:
h[:,1:2]                                         ### Indexing of column without indexing row

array([[0.5573432 ],
       [0.23636635],
       [0.03560241]])

In [406]:
h[:,1:4:1]   ## Similar to 1D ones

array([[0.5573432 , 0.05008743, 0.5698604 ],
       [0.23636635, 0.23313624, 0.85285662],
       [0.03560241, 0.91137179, 0.33176297]])

In [405]:
h[:,1:4:2]

array([[0.5573432 , 0.5698604 ],
       [0.23636635, 0.85285662],
       [0.03560241, 0.33176297]])

************************************

In [304]:
np.transpose(h)                 ## Transpose of matrix; rows into columns; columns into rows

array([[0.43916365, 0.59771317, 0.71056969],
       [0.70494052, 0.16144546, 0.049865  ],
       [0.68099393, 0.27637699, 0.25944605],
       [0.05276461, 0.22350937, 0.24123075]])

In [302]:
## Done; if these basics are cleared; one can solve advanced problems definitely